# Generated by Django 5.1.7 on 2025-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_department_employee_attendance_apology_leaves_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
