# Generated by Django 5.2.2 on 2025-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_department_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="face_encoding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
